// <auto-generated />
using System;
using LearningPlatform.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearningPlatform.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418205950_RecommendationsWeighted")]
    partial class RecommendationsWeighted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryCourse", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer")
                        .HasColumnName("categories_id");

                    b.Property<int>("CoursesId")
                        .HasColumnType("integer")
                        .HasColumnName("courses_id");

                    b.HasKey("CategoriesId", "CoursesId")
                        .HasName("pk_course_categories");

                    b.HasIndex("CoursesId")
                        .HasDatabaseName("ix_course_categories_courses_id");

                    b.ToTable("course_categories", (string)null);
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_courses_author_id");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_courses_level", "level IN ('Beginner','Intermediate','Advanced')");

                            t.HasCheckConstraint("ck_courses_price", "price >= 0");

                            t.HasCheckConstraint("ck_courses_status", "status IN ('Draft','Published')");
                        });
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_enrollments_course_id");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_student_id_course_id");

                    b.ToTable("enrollments", null, t =>
                        {
                            t.HasCheckConstraint("ck_enrollments_progress", "progress BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("CourseId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_course_id_order_number");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.LessonProgress", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_id");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EnrollmentId", "LessonId")
                        .HasName("pk_lesson_progress");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lesson_progress_lesson_id");

                    b.ToTable("lesson_progress", (string)null);
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_payments_course_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_payments_student_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount >= 0");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('Completed','Refunded')");
                        });
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Payout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_payouts");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_payouts_teacher_id");

                    b.ToTable("payouts", null, t =>
                        {
                            t.HasCheckConstraint("ck_payouts_amount", "amount >= 0");

                            t.HasCheckConstraint("ck_payouts_status", "status IN ('Pending','Approved','Rejected','Paid')");
                        });
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_id");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_enrollment_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_grade", "grade BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.TeacherProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.HasKey("UserId")
                        .HasName("pk_teacher_profiles");

                    b.ToTable("teacher_profiles", (string)null);
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Admin','Teacher','Student')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('Active','Suspended')");
                        });
                });

            modelBuilder.Entity("CategoryCourse", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_categories_categories_categories_id");

                    b.HasOne("LearningPlatform.Api.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_categories_courses_courses_id");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Course", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.TeacherProfile", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_teacher_profiles_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Enrollment", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_courses_course_id");

                    b.HasOne("LearningPlatform.Api.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_users_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Lesson", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.LessonProgress", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.Enrollment", "Enrollment")
                        .WithMany("LessonProgress")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_progress_enrollments_enrollment_id");

                    b.HasOne("LearningPlatform.Api.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_progress_lessons_lesson_id");

                    b.Navigation("Enrollment");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Payment", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_courses_course_id");

                    b.HasOne("LearningPlatform.Api.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Payout", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.TeacherProfile", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payouts_teacher_profiles_teacher_id");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Review", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.Enrollment", "Enrollment")
                        .WithOne("Review")
                        .HasForeignKey("LearningPlatform.Api.Models.Review", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_enrollments_enrollment_id");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.TeacherProfile", b =>
                {
                    b.HasOne("LearningPlatform.Api.Models.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("LearningPlatform.Api.Models.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.Enrollment", b =>
                {
                    b.Navigation("LessonProgress");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("LearningPlatform.Api.Models.User", b =>
                {
                    b.Navigation("TeacherProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
